name: flight_booking_sys
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.9.2+11

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  # pusher_client:
  image_gallery_saver:
  flutter_pusher_client:
    git:
      url: https://github.com/mannysoft/flutter-pusher-client.git
  google_api_availability:
  image_compression: ^1.0.3
  badges: ^2.0.2
  path_provider:
  permission_handler: ^8.3.0
  url_launcher:
  flutter_cache_manager:
  firebase_core: ^1.10.6
  firebase_messaging: ^11.2.4
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  select_form_field:

  cupertino_icons: ^1.0.2
  shimmer: ^2.0.0
  mime_type: ^1.0.0
  clippy_flutter: ^2.0.0-nullsafety.1
  auto_animated:
  images_picker:
  cached_network_image: ^3.1.0
  scroll_to_index:
  photo_view:
  random_password_generator: ^0.2.1
  flutter_bootstrap: ^2.0.0
  get:
  flex_color_scheme:
  google_fonts:
  keyboard_dismisser:
  get_storage:
  supercharged:
  csv:
  data_connection_checker_tv:
  dropdown_search: ^2.0.0
  dartz:
  carousel_slider: ^4.0.0
  extended_image: ^6.2.1
  dots_indicator: ^2.0.0
  dio:

  loading_animations:
  simple_animations: 3.1.1
  timeago: ^3.1.0
  flutter_portal:
  logger:
  intl:
  animated_theme_switcher:

dev_dependencies:
  flutter_launcher_icons: "^0.11.0"
  flutter_app_name: ^0.1.0
  flutter_native_splash:

  flutter_test:
    sdk: flutter
flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/educationloco.jpg"
flutter_app_name:
  name: "application "
flutter_native_splash:
  color: "#f0f0f0"
  image: assets/educationloco.jpg
  android: true
  ios: true
  web: false
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  assets:
    - assets/
  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  fonts:
    - family: CustomIcon
      fonts:
        - asset: fonts/CustomIcon.ttf
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
